ci: Add CI of of linux platform
dyne/Zenroom pull request #164
Opened 2021-03-02 03:20 UTC by splasky

There are several platforms that Zenroom support. Some changes on
other specific platform may not easily to check such as cortex m.

This commit adds a CI of linux platform to check Zenroom will work
correctly.

2021-03-16 09:29 UTC, puria requested changes
I'd rather prefer to have `crypto-check` here in place of platform specific, with a matrix.os including other platforms (mac, windows), what you think?

2021-03-16 09:55 UTC, splasky commented
> I'd rather prefer to have `crypto-check` here in place of platform specific, with a matrix.os including other platforms (mac, windows), what you think?

Great idea! Let me modify it.

2021-03-22 07:46 UTC, splasky commented
@jaromil The CI may fail to build on macOS. Can you check it?

2021-03-22 07:50 UTC, splasky commented
By the way, the travis CI will fail since the modified for src/cli.c inside commit 14e4103.

2021-03-23 14:45 UTC, puria approved these changes

2021-03-24 09:45 UTC, merged

2021-03-24 09:46 UTC, jaromil commented
many thanks!! this is a great achievement to prove functioning on cortex chips